## Introduction to pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
dict1 = {
    "name":["Damaru", "Kaushal", "Sonam", "Nirjal", "Tiraj"],
    "marks":[92,34,24,67,0],
    "city":["Biratnagar", "Pathri", "Damak", "Biratchowck", "Jungle"]
}

In [5]:
df = pd.DataFrame(dict1)

In [6]:
df

      name  marks         city
0   Damaru     92   Biratnagar
1  Kaushal     34       Pathri
2    Sonam     24        Damak
3   Nirjal     67  Biratchowck
4    Tiraj      0       Jungle

In [7]:
 df.to_csv("damaru_index_false.csv", index = False)

In [8]:
df.to_csv("damaru.csv")

In [9]:
df.head(2)

      name  marks        city
0   Damaru     92  Biratnagar
1  Kaushal     34      Pathri

In [10]:
df.tail(2)

     name  marks         city
3  Nirjal     67  Biratchowck
4   Tiraj      0       Jungle

In [11]:
df.describe()

           marks
count   5.000000
mean   43.400000
std    36.287739
min     0.000000
25%    24.000000
50%    34.000000
75%    67.000000
max    92.000000

In [12]:
#lets read one csv file that you have i have one file lets do it in courses.csv
jcb = pd.read_csv("courses.csv")

In [13]:
jcb

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [16]:
 df=pd.DataFrame(jcb,index=['a','b','c','d','e','f','g','h','i','j','k'])

In [17]:
df

   course_id course_name  price
a        NaN         NaN    NaN
b        NaN         NaN    NaN
c        NaN         NaN    NaN
d        NaN         NaN    NaN
e        NaN         NaN    NaN
f        NaN         NaN    NaN
g        NaN         NaN    NaN
h        NaN         NaN    NaN
i        NaN         NaN    NaN
j        NaN         NaN    NaN
k        NaN         NaN    NaN

# Series and Dataframe

In [18]:
ser = pd.Series(np.random.rand(20))

In [19]:
type(ser)

pandas.Series

In [20]:
ser

0     0.229285
1     0.238402
2     0.187901
3     0.252685
4     0.012121
5     0.938574
6     0.976683
7     0.228754
8     0.149809
9     0.702412
10    0.431010
11    0.610309
12    0.713986
13    0.854052
14    0.583536
15    0.482244
16    0.718526
17    0.142521
18    0.612120
19    0.745037
dtype: float64

In [21]:
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

In [22]:
newdf

            0         1         2         3         4
0    0.181715  0.686549  0.622328  0.853666  0.071764
1    0.968379  0.890942  0.838730  0.403526  0.130723
2    0.025677  0.914537  0.102736  0.920375  0.391216
3    0.593993  0.393598  0.344209  0.164594  0.104905
4    0.646655  0.525299  0.121577  0.643361  0.147251
..        ...       ...       ...       ...       ...
329  0.124950  0.025616  0.292522  0.167674  0.141082
330  0.386608  0.193963  0.518992  0.005438  0.430356
331  0.723051  0.097174  0.594207  0.035767  0.658622
332  0.140667  0.529634  0.226657  0.982922  0.102282
333  0.877473  0.859706  0.521200  0.834084  0.764900

[334 rows x 5 columns]

In [23]:
type(newdf)

pandas.DataFrame

In [24]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.482986    0.506517    0.501350    0.498872    0.534233
std      0.289234    0.294060    0.299607    0.301039    0.283319
min      0.008396    0.001578    0.000048    0.005438    0.001664
25%      0.244994    0.240077    0.241584    0.225666    0.299701
50%      0.470237    0.508461    0.504358    0.494583    0.558024
75%      0.744909    0.764065    0.772708    0.760116    0.768028
max      0.996982    0.999598    0.998480    0.989409    0.995303

In [25]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [26]:
newdf.tail()

            0         1         2         3         4
329  0.124950  0.025616  0.292522  0.167674  0.141082
330  0.386608  0.193963  0.518992  0.005438  0.430356
331  0.723051  0.097174  0.594207  0.035767  0.658622
332  0.140667  0.529634  0.226657  0.982922  0.102282
333  0.877473  0.859706  0.521200  0.834084  0.764900

In [27]:
newdf.head()

          0         1         2         3         4
0  0.181715  0.686549  0.622328  0.853666  0.071764
1  0.968379  0.890942  0.838730  0.403526  0.130723
2  0.025677  0.914537  0.102736  0.920375  0.391216
3  0.593993  0.393598  0.344209  0.164594  0.104905
4  0.646655  0.525299  0.121577  0.643361  0.147251

In [28]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [29]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [30]:
#convering to numpy aray
newdf.to_numpy()

array([[0.18171544, 0.68654852, 0.62232758, 0.85366572, 0.07176357],
       [0.96837936, 0.89094155, 0.83873012, 0.40352589, 0.1307226 ],
       [0.02567747, 0.91453685, 0.10273616, 0.92037484, 0.3912163 ],
       ...,
       [0.72305144, 0.09717422, 0.59420663, 0.03576745, 0.65862162],
       [0.14066735, 0.52963389, 0.22665712, 0.98292235, 0.10228201],
       [0.87747261, 0.859706  , 0.52120034, 0.83408401, 0.76490033]],
      shape=(334, 5))

In [31]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.181715,0.968379,0.025677,0.593993,0.646655,0.312178,0.055191,0.740430,0.846447,0.605805,...,0.965521,0.223944,0.030361,0.344885,0.840994,0.124950,0.386608,0.723051,0.140667,0.877473
1,0.686549,0.890942,0.914537,0.393598,0.525299,0.651846,0.585211,0.183782,0.201878,0.311876,...,0.478410,0.592598,0.969127,0.492564,0.310028,0.025616,0.193963,0.097174,0.529634,0.859706
2,0.622328,0.838730,0.102736,0.344209,0.121577,0.308796,0.166197,0.391272,0.571875,0.312610,...,0.479239,0.819672,0.064611,0.832577,0.772348,0.292522,0.518992,0.594207,0.226657,0.521200
3,0.853666,0.403526,0.920375,0.164594,0.643361,0.971824,0.558937,0.256220,0.010407,0.462963,...,0.674750,0.045674,0.417942,0.048274,0.423039,0.167674,0.005438,0.035767,0.982922,0.834084
4,0.071764,0.130723,0.391216,0.104905,0.147251,0.635735,0.601978,0.276712,0.615842,0.349617,...,0.742531,0.805185,0.630985,0.962038,0.924016,0.141082,0.430356,0.658622,0.102282,0.764900

In [32]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [33]:
newdf.head()

          0         1         2         3         4
0  0.181715  0.686549  0.622328  0.853666  0.071764
1  0.968379  0.890942  0.838730  0.403526  0.130723
2  0.025677  0.914537  0.102736  0.920375  0.391216
3  0.593993  0.393598  0.344209  0.164594  0.104905
4  0.646655  0.525299  0.121577  0.643361  0.147251

# Sorting using axis concept of numpy

In [34]:
newdf.sort_index(axis=0, ascending = False)

            0         1         2         3         4
333  0.877473  0.859706  0.521200  0.834084  0.764900
332  0.140667  0.529634  0.226657  0.982922  0.102282
331  0.723051  0.097174  0.594207  0.035767  0.658622
330  0.386608  0.193963  0.518992  0.005438  0.430356
329  0.124950  0.025616  0.292522  0.167674  0.141082
..        ...       ...       ...       ...       ...
4    0.646655  0.525299  0.121577  0.643361  0.147251
3    0.593993  0.393598  0.344209  0.164594  0.104905
2    0.025677  0.914537  0.102736  0.920375  0.391216
1    0.968379  0.890942  0.838730  0.403526  0.130723
0    0.181715  0.686549  0.622328  0.853666  0.071764

[334 rows x 5 columns]

In [35]:
newdf.sort_index(axis=0)

            0         1         2         3         4
0    0.181715  0.686549  0.622328  0.853666  0.071764
1    0.968379  0.890942  0.838730  0.403526  0.130723
2    0.025677  0.914537  0.102736  0.920375  0.391216
3    0.593993  0.393598  0.344209  0.164594  0.104905
4    0.646655  0.525299  0.121577  0.643361  0.147251
..        ...       ...       ...       ...       ...
329  0.124950  0.025616  0.292522  0.167674  0.141082
330  0.386608  0.193963  0.518992  0.005438  0.430356
331  0.723051  0.097174  0.594207  0.035767  0.658622
332  0.140667  0.529634  0.226657  0.982922  0.102282
333  0.877473  0.859706  0.521200  0.834084  0.764900

[334 rows x 5 columns]

In [36]:
newdf.sort_index(axis=1)

            0         1         2         3         4
0    0.181715  0.686549  0.622328  0.853666  0.071764
1    0.968379  0.890942  0.838730  0.403526  0.130723
2    0.025677  0.914537  0.102736  0.920375  0.391216
3    0.593993  0.393598  0.344209  0.164594  0.104905
4    0.646655  0.525299  0.121577  0.643361  0.147251
..        ...       ...       ...       ...       ...
329  0.124950  0.025616  0.292522  0.167674  0.141082
330  0.386608  0.193963  0.518992  0.005438  0.430356
331  0.723051  0.097174  0.594207  0.035767  0.658622
332  0.140667  0.529634  0.226657  0.982922  0.102282
333  0.877473  0.859706  0.521200  0.834084  0.764900

[334 rows x 5 columns]

In [37]:
newdf.sort_index(axis=1, ascending = False)

            4         3         2         1         0
0    0.071764  0.853666  0.622328  0.686549  0.181715
1    0.130723  0.403526  0.838730  0.890942  0.968379
2    0.391216  0.920375  0.102736  0.914537  0.025677
3    0.104905  0.164594  0.344209  0.393598  0.593993
4    0.147251  0.643361  0.121577  0.525299  0.646655
..        ...       ...       ...       ...       ...
329  0.141082  0.167674  0.292522  0.025616  0.124950
330  0.430356  0.005438  0.518992  0.193963  0.386608
331  0.658622  0.035767  0.594207  0.097174  0.723051
332  0.102282  0.982922  0.226657  0.529634  0.140667
333  0.764900  0.834084  0.521200  0.859706  0.877473

[334 rows x 5 columns]

In [38]:
#Accessing index
newdf[0]

0      0.181715
1      0.968379
2      0.025677
3      0.593993
4      0.646655
         ...
329    0.124950
330    0.386608
331    0.723051
332    0.140667
333    0.877473
Name: 0, Length: 334, dtype: float64

In [39]:
type(newdf)

pandas.DataFrame

In [40]:
type(newdf[0])

pandas.Series

# View vs Copy

In [42]:
newdf2 = newdf

In [47]:
newdf[0,0]  = 978

In [48]:
newdf

       0         1         2         3         4  (0, 0)
0    978  0.686549  0.622328  0.853666  0.071764     978
1    978  0.890942  0.838730  0.403526  0.130723     978
2    978  0.914537  0.102736  0.920375  0.391216     978
3    978  0.393598  0.344209  0.164594  0.104905     978
4    978  0.525299  0.121577  0.643361  0.147251     978
..   ...       ...       ...       ...       ...     ...
329  978  0.025616  0.292522  0.167674  0.141082     978
330  978  0.193963  0.518992  0.005438  0.430356     978
331  978  0.097174  0.594207  0.035767  0.658622     978
332  978  0.529634  0.226657  0.982922  0.102282     978
333  978  0.859706  0.521200  0.834084  0.764900     978

[334 rows x 6 columns]

In [49]:
newdf3 = newdf.copy()

In [51]:
newdf3[0] = 77

In [52]:
newdf3

      0         1         2         3         4  (0, 0)
0    77  0.686549  0.622328  0.853666  0.071764     978
1    77  0.890942  0.838730  0.403526  0.130723     978
2    77  0.914537  0.102736  0.920375  0.391216     978
3    77  0.393598  0.344209  0.164594  0.104905     978
4    77  0.525299  0.121577  0.643361  0.147251     978
..   ..       ...       ...       ...       ...     ...
329  77  0.025616  0.292522  0.167674  0.141082     978
330  77  0.193963  0.518992  0.005438  0.430356     978
331  77  0.097174  0.594207  0.035767  0.658622     978
332  77  0.529634  0.226657  0.982922  0.102282     978
333  77  0.859706  0.521200  0.834084  0.764900     978

[334 rows x 6 columns]

In [53]:
newdf

       0         1         2         3         4  (0, 0)
0    978  0.686549  0.622328  0.853666  0.071764     978
1    978  0.890942  0.838730  0.403526  0.130723     978
2    978  0.914537  0.102736  0.920375  0.391216     978
3    978  0.393598  0.344209  0.164594  0.104905     978
4    978  0.525299  0.121577  0.643361  0.147251     978
..   ...       ...       ...       ...       ...     ...
329  978  0.025616  0.292522  0.167674  0.141082     978
330  978  0.193963  0.518992  0.005438  0.430356     978
331  978  0.097174  0.594207  0.035767  0.658622     978
332  978  0.529634  0.226657  0.982922  0.102282     978
333  978  0.859706  0.521200  0.834084  0.764900     978

[334 rows x 6 columns]

# Loc and iloc

In [54]:
newdf.loc[0,0] = 654

In [55]:
newdf.head()

     0         1         2         3         4  (0, 0)
0  654  0.686549  0.622328  0.853666  0.071764     978
1  978  0.890942  0.838730  0.403526  0.130723     978
2  978  0.914537  0.102736  0.920375  0.391216     978
3  978  0.393598  0.344209  0.164594  0.104905     978
4  978  0.525299  0.121577  0.643361  0.147251     978